name = "pesde/crunchydare"
version = "0.0.0"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/crunchydare"
license = "MIT"
private = true

[target]
environment = "roblox"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"
darklua-build = ".pesde/darklua_build/darklua_build.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[engines]
lune = "^0.9.4"
pesde = "^0.7.0-rc.1"

[dev_dependencies]
scripts = { name = "jiwonz/pesde_scripts_rojo", version = "^0.1.0-rc.1", target = "lune" }
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0-rc.7", target = "lune" }
dirs = { name = "jiwonz/dirs", version = "^0.5.1", target = "lune" }
base91-luau = { name = "jiwonz/base91", version = "^0.1.0-rc.1", target = "luau" }
squash-luau = { name = "jiwonz/squash", version = "^3.0.0-rc.1", target = "luau" }
darklua_build = { repo = "jiwonz/lune_darklua_build", rev = "1bf7fc3" }

[dependencies]
crunchyroll = { wally = "ffrostfall/crunchyroll", version = "^0.1.0" }
base91 = { name = "jiwonz/base91", version = "^0.1.0-rc.1" }
squash = { name = "jiwonz/squash", version = "^3.0.0-rc.1" }

[patches]
"wally#ffrostfall/crunchyroll" = { "0.1.0 roblox" = "patches/wally#ffrostfall+crunchyroll-0.1.0+roblox.patch" }
