# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "UpliftGames/rojo@7.5.1-uplift.syncback.rc.21"
ovjo = "jiwonz/ovjo@0.0.10"
selene = "Kampfkarren/selene@0.28.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.52.1"
stylua = "JohnnyMorganz/StyLua@2.1.0"
darklua = "seaofvoices/darklua@0.16.0"
anim2rbx = "jiwonz/anim2rbx@0.2.0"
